Updated navigation & join metagame
MetaFam/metagame-wiki pull request #300
Opened 2021-09-23 13:02 UTC by peth-yursick

This pull request updates:
- The navigation board post with a new link to the new board & removal of outdated info
- The join metagame page with removal of the typeform as decided on the innkeepers call & replacement of it with a newsletter subscription form

2021-09-28 12:37 UTC, peth-yursick commented
halp plz @luxumbra @Baconaetor

2021-09-28 12:40 UTC, luxumbra commented
> halp plz @luxumbra @Baconaetor

I didn't want to tread on Bacons toes with this but can take a look

2021-09-28 17:35 UTC, luxumbra requested changes
I have fixed the build but for some reason, the styling of the wiki sidebar is broken. Looking into it.

2021-09-28 23:20 UTC, Baconaetor reviewed
It's the point here because it's directing you to the sidebar as you're already on the page. Long term I think I just want to update this with the new icons like on MyMeta.

2021-09-28 23:21 UTC, Baconaetor commented
> 
> 
> > halp plz @luxumbra @Baconaetor
> 
> I didn't want to tread on Bacons toes with this but can take a look

Lol you're good, I don't know why I keep missing these. Gotta figure out how to get better notifications somehow.

2021-09-28 23:22 UTC, Baconaetor commented
> 
> 
> I have fixed the build but for some reason, the styling of the wiki sidebar is broken. Looking into it.

Yeah this is weird. What was wrong with the build to start?

2021-09-29 00:07 UTC, luxumbra commented
> > I have fixed the build but for some reason, the styling of the wiki sidebar is broken. Looking into it.
> 
> Yeah this is weird. What was wrong with the build to start?

The sidebars file was throwing an error due to the 300 in the `300-of-metagame.md` file not gettng picked up and there was a style attribute in one of the iframes peth added which made the md file invalid.

2021-09-29 11:00 UTC, peth-yursick commented
Thank you @luxumbra, seems to be working now?

2021-09-29 11:28 UTC, luxumbra reviewed
Looks like this is fixed. @Baconaetor or @peth-yursick can you please verify that the breakage is now resolved. 🙏🏻 Then we can merge

2021-09-29 11:28 UTC, luxumbra commented on src/css/custom.scss
> +.main-wrapper [class^='docSidebarContainer'] {
This was the cause of breaking styling with the sidebar. Docusaurus is spitting our slightly different html & attributes (swapped `<div role="complementary">` for `<aside>`)

2021-09-29 11:32 UTC, luxumbra approved these changes

2021-09-29 11:39 UTC, merged

2021-09-29 11:40 UTC, luxumbra commented
> It's the point here because it's directing you to the sidebar as you're already on the page. Long term I think I just want to update this with the new icons like on MyMeta.

So you think 👈🏻  should stay? On the playbooks call the other day the general consensus was "why the f would you use a pointy finger?!" and to replace it with books. 😅

2021-09-29 16:55 UTC, Baconaetor commented
> 
> 
> > It's the point here because it's directing you to the sidebar as you're already on the page. Long term I think I just want to update this with the new icons like on MyMeta.
> 
> So you think 👈🏻 should stay? On the playbooks call the other day the general consensus was "why the f would you use a pointy finger?!" and to replace it with books. 😅

Lol yeah, it's not great. I would have kept it for the time being as it prevents it from looking like a dead link. When you click it nothing happens, so the point helped direct you to the fact you're already there. That whole app drawer needs to change though. We need a new homepage for the wiki desperately. I just can't think of a good idea for one. . .

2021-09-29 17:03 UTC, luxumbra commented
> > > It's the point here because it's directing you to the sidebar as you're already on the page. Long term I think I just want to update this with the new icons like on MyMeta.
> > 
> > 
> > So you think 👈🏻 should stay? On the playbooks call the other day the general consensus was "why the f would you use a pointy finger?!" and to replace it with books. sweat_smile
> 
> Lol yeah, it's not great. I would have kept it for the time being as it prevents it from looking like a dead link. When you click it nothing happens, so the point helped direct you to the fact you're already there. That whole app drawer needs to change though. We need a new homepage for the wiki desperately. I just can't think of a good idea for one. . .

Dammit lol it's been merged already. 🤦🏻  Hard to know how much work to put into it when we are meant to be migrating the wiki away from Docusaurus. Agreed though, the current landing page would be great. Wouldn't be too hard to improve on the current one.

2021-09-30 13:22 UTC, peth-yursick commented
> so the point helped direct you to the fact you're already there. That whole app drawer needs to change though. We need a new homepage for the wiki desperately. I just can't think of a good idea for one. . .

Yep, that's precisely the reason I used it. The app drawer needs to go but I think the landing page for the wiki itself should simply be a nicer way to display all the categories. Maybe similar to how playbooks are displayed but wider?

![image](https://user-images.githubusercontent.com/55857222/135463147-68d18068-be7e-4d7b-bd8f-c72afb86075b.png)

This is a bit too wide but you get the idea.. Will need a designer on it.

MetaGame itself will have a new landing page & the wiki will be one of the things accessed through the menu above & then different pieces will I guess over time be taken out of the wiki (eg. Playbooks & Great Houses) to be put in their own place.

> Hard to know how much work to put into it when we are meant to be migrating the wiki away from Docusaurus.

For Playbooks yes, but didn't we agree for the wiki itself to only upgrade it to Docusaurus v2?

2021-10-01 03:14 UTC, Baconaetor commented
> 
> 
> > so the point helped direct you to the fact you're already there. That whole app drawer needs to change though. We need a new homepage for the wiki desperately. I just can't think of a good idea for one. . .
> 
> Yep, that's precisely the reason I used it. The app drawer needs to go but I think the landing page for the wiki itself should simply be a nicer way to display all the categories. Maybe similar to how playbooks are displayed but wider?
> 
> ![image](https://user-images.githubusercontent.com/55857222/135463147-68d18068-be7e-4d7b-bd8f-c72afb86075b.png)
> 
> This is a bit too wide but you get the idea.. Will need a designer on it.
> 
> MetaGame itself will have a new landing page & the wiki will be one of the things accessed through the menu above & then different pieces will I guess over time be taken out of the wiki (eg. Playbooks & Great Houses) to be put in their own place.
> 
> > Hard to know how much work to put into it when we are meant to be migrating the wiki away from Docusaurus.
> 
> For Playbooks yes, but didn't we agree for the wiki itself to only upgrade it to Docusaurus v2?

Oooh, I'm liking this. I can work with that. Also yeah, we need more clarity on the Docusaurus stuff. Are we still on V1 currently? Also, who's making that call?