create metaos page on the what we do
MetaFam/metagame-wiki pull request #319
Opened 2021-12-01 11:47 UTC by peth-yursick

2021-12-03 01:32 UTC, luxumbra requested changes
Nice read but there's no sidebars.js update, so when you view the page it has no sidebar. Also, the Frontmatter *must* be added on the *first* line of the file, otherwise it wont treat it as Frontmatter and will render the contents to the page. 

![image](https://user-images.githubusercontent.com/780350/144529315-16a6e815-5e34-47a6-9381-c9842eca85c6.png)

2021-12-03 01:33 UTC, luxumbra commented on docs/what-we-do/metaos.md
> +
This line needs to be removed to make the `title` in the Frontmatter render as it should.

2021-12-03 01:34 UTC, luxumbra commented
If you don't fancy doing the fixes on this @peth-yursick, let us know.

2021-12-04 10:38 UTC, peth-yursick commented
Thank you. The sidebar update comes in #320, I didn't want to create another PR just for the sidebar update & I knew the desktop app would be annoying 😅

2021-12-04 11:57 UTC, luxumbra approved these changes
LGTM.

2021-12-04 11:58 UTC, merged